### ISSUE TITLE
05_Loss_Functions.ipynb function missing

### ISSUE THREAD

**Issue by pengfei123xiao** [groverpr/Intro-to-Machine-Learning#1]
Hi,
I am currently reading your code in 05_Loss_Functions.ipynb.
It is very great except that there seems to miss a function name 'expo' in the Exponential Loss part.

Thanks.

**Comment by groverpr** [comment]
Rectified in commit: https://github.com/groverpr/Machine-Learning/commit/44c4c2bdbd5ae0344faa32eeba6ca20cd30f4ad7. Thanks!
