### ISSUE TITLE
Recommended config

### ISSUE THREAD

**Issue by shantanuo** [groverpr/Intro-to-Machine-Learning#3]
Tried to run the code as shown here...

https://github.com/groverpr/Machine-Learning/blob/master/notebooks/10_Transfer_Learn_MXNet.ipynb

Could not run beyond this line...

```
In [82]:
net1 = CustomSeqNet(input_output_embed_map, dense_sizes, dropouts, activation)
In [83]:
net1.initialize(mx.init.Xavier(), ctx=ctx, force_reinit=True)  # initialize network
```

Kernel died. Using AWS EC2 instance type i3.xlarge 

What is recommended config?

**Comment by groverpr** [comment]
You can use CPU instead of GPU. i.e. in `In [34]:` `ctx = [mx.cpu()]`. It is probably dying because GPU setup in your instance has issues. (Sorry for very late reply. I didn't check this repository for a long time.)
